### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jjlopez** [awsmug/awesome-forms#16]
Hello.

I have the Spanish translation. How I can add the file .po to the plugin?
Maybe I can do it through a pull request.

Greetings!

**Comment by mahype** [comment]
Hello Jonathan,

great! Thank you for translating! You can send it to me by Email. I will
put it to my translation database.

Greetings,

Sven Wagener

*Awesome UG*
WordPress Plugin Factory

Krepperweg 4
40724 Hilden

Mobil +49 (0) 151 / 546 755 96
sven@awesome.ug
www.awesome.ug

2015-07-22 2:50 GMT+02:00 Jonathan López <notifications@github.com>:

**Comment by jjlopez** [comment]
Well as soon as possible I send the file.

Greetings!

**Comment by mahype** [comment]
Thats great! Thank you! :)
