### ISSUE TITLE
How to add new Question Form Elements?

### ISSUE THREAD

**Issue by fcbuss** [awsmug/awesome-forms#27]
Hi all,
I need to add <b>questions with a 1 to 10 answer range</b> to my survey. In order to save space and to make it look better I tried to make a <b>horizontal OneChoice Element</b> (answers in a row).
That is how I did it:
1. I copied the <b>onechoice.php</b> and named it to <b>onechoice_horizontal.php</b> and deleted the p-tag to show the answers in a row. I also adapted _Horizontal where needed.
2. I added the <b>onechoice_horizontal.php</b> to <b>component.php</b>
3. I copied the <b>OneChoice element in testing/main.php</b> and <b>added _Horizontal</b>

My problem now is, that the new element shows up in the WordPress admin section and I can drag i to my survey and change the question name an add answers. But: <b>after saving it, the new element disappears.</b> I am not able to find it neither in the admin nor in the frontend. The only place where the new element shows up is in the database under XXX_questions_questions. What should I do?

**Comment by mahype** [comment]
Hello,

do you have changed the ID of the element? Can you send me the code of the element?

Greetings,

Sven

**Comment by fcbuss** [comment]
Hello Sven,
no, I did not change the ID. Where should I do that? 
You can find your adapted plugin here: https://www.dropbox.com/s/2trg49k298lhmw8/questions.zip?dl=0
Thank you very much for helping me!
Christian

**Comment by fcbuss** [comment]
Oh I already find out how. I added a settings field to the onechoice element and an if/else to the input_html and it works perfectly - thank you for your help :)
