### ISSUE TITLE
Email validation failed on correct email address

### ISSUE THREAD

**Issue by babs-barre** [awsmug/awesome-forms#42]
Reporting that the validation of valid email addresses for the domain me.com failed.

E.g. : aawa@me.com
![image](https://cloud.githubusercontent.com/assets/3924054/10933680/957cd97a-82da-11e5-8a57-de8f6e4d5d2b.png)

(Using version 1.0.0 beta 20)

**Comment by mahype** [comment]
I will take a look at this! Thank you for helping! :)
