### ISSUE TITLE
Tabs in Metaboxes not working

### ISSUE THREAD

**Issue by mahype** [awsmug/awesome-forms#44]
Since the last JS Script update, the Tabs in the Meta boxes are not working anymore.

**Comment by felixarntz** [comment]
weird, they worked for me. We might need to debug it together

**Comment by mahype** [comment]
No Problem I found the issue. Take a look here:

https://github.com/awsmug/awesome-forms/commit/fc608b341ff197e63768cd3bd19eafe4aa0b9ffe
