### ISSUE TITLE
fix `af_is_formbuilder()` function

### ISSUE THREAD

**Issue by felixarntz** [awsmug/awesome-forms#72]
See [this line](https://github.com/awsmug/awesome-forms/blob/master/functions.php#L73)...

Why is line 72 commented out? You probably forgot something there, since line 73 just checks if we're in the admin. This function being incorrect also causes some PHP notices in the backend.

**Comment by mahype** [comment]
This was a hot hot fix. I will put in the check in the next hours back.

**Comment by felixarntz** [comment]
ok

**Comment by mahype** [comment]
Done
